// Tarifario de MANO DE OBRA — Mecánica. Compacto = Hyundai Grand i10 / Kia Soluto.
// Fuente: Excel "PRECIOS DE MANO DE OBRA mecánica y chapistería" (sept 2026).
// `precio` = precio de lista (lo que se cobra). `edison` = costo interno del mecánico
// (INTERNO, no se cita al cliente). El agente de WhatsApp NO cotiza estos montos.

export type ItemMecanica = {
  concepto: string;
  /** Precio de lista a cobrar (USD). null = a confirmar por el taller. */
  precio: number | null;
  /** Costo interno de mano de obra (mecánico Edison). Solo referencia interna. */
  edison: number | null;
};

export const VEHICULO_TARIFA_MECANICA = "Compacto (Grand i10 / Kia Soluto)";

export const TARIFAS_MECANICA: ItemMecanica[] = [
  { concepto: "KIT DE TIEMPOS CARRO AUTOMATICO GRAND I10 Y KIA SOLUTO", precio: 232, edison: null },
  { concepto: "KIT DE TIEMPOS CARRO MANUAL GRAND I10 Y KIA SOLUTO", precio: 212, edison: 60 },
  { concepto: "Cambio de Campana", precio: null, edison: 15 },
  { concepto: "Cambio / Revisión de Amortiguadores delanteros C/U", precio: 25, edison: 20 },
  { concepto: "Cambio / Revisión de Amortiguadores traseros C/U", precio: 25, edison: 10 },
  { concepto: "Cambio de Aceite de transmisiones 80/90", precio: 15, edison: null },
  { concepto: "Revision de luces delanteras y traseras / cambio de bombillos", precio: 10, edison: null },
  { concepto: "Cambio de Balineras Delanteras", precio: 25, edison: 25 },
  { concepto: "Cambio de Base de Motor", precio: 15, edison: null },
  { concepto: "Cambio de empaque de tapa valvulas", precio: 25, edison: 10 },
  { concepto: "Cambio de Retenedora Delantera de Trasmisión", precio: null, edison: null },
  { concepto: "Cambio de Retenedora Trasera de Cigüeñal", precio: 75, edison: null },
  { concepto: "Cambio de Cable de Clutch", precio: 25, edison: null },
  { concepto: "Cambio de Kit de Clutch con retenedora trasera de cigüeñal", precio: 75, edison: 60 },
  { concepto: "Cambio de Sensor de Arbol de Leva", precio: 25, edison: null },
  { concepto: "Cambio de Sensor de Posicion del Cigüeñal", precio: 15, edison: null },
  { concepto: "Cambio de Valvula de Temperatura (ECT)", precio: 10, edison: null },
  { concepto: "Cambio de Valvula IAC", precio: 10, edison: null },
  { concepto: "Cambio de Valvula MAP", precio: 10, edison: null },
  { concepto: "Cambio de Valvula TPS", precio: 10, edison: null },
  { concepto: "Bajar,Desarmar y Armar Caja de Transmisiones", precio: 90, edison: 120 },
  { concepto: "Desmontar y Montar Alternador", precio: 25, edison: 20 },
  { concepto: "Desmontar y Montar Motor de Arranque", precio: 25, edison: null },
  { concepto: "Desmontar y Montar Base del Termostato / Cambio", precio: 30, edison: 25 },
  { concepto: "Desmontar y Montar Base Inferior de la Trasmisión (avioncito)", precio: 15, edison: null },
  { concepto: "Desmontar y Montar Bomba de Gasolina", precio: 45, edison: null },
  { concepto: "Desmontar y Montar Booster de Frenos", precio: 40, edison: null },
  { concepto: "Desmontar y Montar Bota de Punta de Flecha", precio: 25, edison: null },
  { concepto: "Desmontar y Montar Brazo Link", precio: 10, edison: 7 },
  { concepto: "Desmontar y Montar Cabezote de Motor", precio: 150, edison: 110 },
  { concepto: "Desmontar y Montar Camarin de Admisión", precio: 40, edison: null },
  { concepto: "Desmontar y Montar Cilindros de Frenos cada lado", precio: 25, edison: null },
  { concepto: "Desmontar y Montar Compresor de A/A", precio: null, edison: null },
  { concepto: "Desmontar y Montar Condensador de A/A", precio: 25, edison: 25 },
  { concepto: "Desmontar y Montar Copa de Transmisión / cada lado", precio: 25, edison: null },
  { concepto: "Desmontar y Montar Eje de Punta de Flecha", precio: 25, edison: null },
  { concepto: "Desmontar y Montar Abanico", precio: 25, edison: 10 },
  { concepto: "Desmontar y Montar Filtro de Gasolina", precio: 45, edison: null },
  { concepto: "Desmontar y Montar Muñequilla", precio: 30, edison: null },
  { concepto: "Desmontar y Montar Radiador", precio: 25, edison: 25 },
  { concepto: "Desmontar y Montar Terminal Externo de Dirección / cada lado", precio: 10, edison: 5 },
  { concepto: "Desmontar y Montar Terminal Interno de cremallera (Rotula) / cada lado", precio: 15, edison: 10 },
  { concepto: "Desmontar y Montar Tricepta o trebol / cada lado", precio: 25, edison: 15 },
  { concepto: "Desmontar y Montar V", precio: 25, edison: 15 },
  { concepto: "Mantenimiento Cambio de Aceite y Filtros", precio: 10, edison: 6 },
  { concepto: "Escaner Diagnostico", precio: 15, edison: 15 },
  { concepto: "Instalación de Cable de Aceleración", precio: 10, edison: null },
  { concepto: "Limpieza Cuerpo de Aceleración", precio: 10, edison: null },
  { concepto: "Limpieza de Tanque de Gasolina", precio: 25, edison: null },
  { concepto: "Limpieza del Sitema de Refrigeración", precio: 15, edison: null },
  { concepto: "Limpieza Superficial de Inyectores c/u", precio: null, edison: null },
  { concepto: "Mantenimiento de Bota de la Tricepta", precio: null, edison: null },
  { concepto: "Purga de Sistema de Enfriamiento", precio: 20, edison: null },
  { concepto: "Rectificación de Volante de Trasmisión", precio: 25, edison: null },
  { concepto: "Revisión de Sistema Electrico", precio: 20, edison: null },
  { concepto: "Revisión y Cambio de Bobina de Encendido", precio: 25, edison: null },
  { concepto: "Cambio de retenedora copa caja o de eje transmision / cada lado", precio: 15, edison: null },
  { concepto: "Cambio de punta de flecha", precio: 25, edison: 20 },
  { concepto: "servicio de Aire Acondicionado ( vacio, carga de gas con aceite )", precio: 35, edison: null },
  { concepto: "Cambio de condensador", precio: 25, edison: null },
  { concepto: "Soldar Condensador de Aire Acondicionado", precio: 10, edison: null },
  { concepto: "Desmontar y Montar Bomba de Aceite (Compra original)", precio: 65, edison: 95 },
  { concepto: "Cambio de Coil de Bobina de Encendido", precio: 15, edison: null },
  { concepto: "Reparacion del embase de agua para limpia parabrisas", precio: null, edison: null },
  { concepto: "Desmontar y Montar Espirales Delanteros / cada lado", precio: 15, edison: null },
  { concepto: "Desmontar y Montar Espirales Traseros / cada lado", precio: 15, edison: null },
  { concepto: "Desmontar y Montar Valvula de Expansion de A/A (NO)", precio: 35, edison: null },
  { concepto: "Cambio de Bandas de Frenos Traseras", precio: 25, edison: null },
  { concepto: "Cambio de Bases de Amortiguador C/U", precio: 10, edison: null },
  { concepto: "Cambio de Tacos de Frenos Delanteras", precio: 10, edison: null },
  { concepto: "Desmontar y Montar Discos de Frenos", precio: 10, edison: 10 },
  { concepto: "Calibración / Cambio de Bujias", precio: 15, edison: 10 },
  { concepto: "Calibración de Valvulas de Motor", precio: null, edison: null },
  { concepto: "Cambio de Cables de Bujias", precio: 10, edison: 5 },
  { concepto: "Cambio de Esparragos de Llantas", precio: 3, edison: null },
  { concepto: "Rotacion de llantas", precio: 5, edison: null },
  { concepto: "Desmontar y Montar Cuerpo de Admisión", precio: 15, edison: null },
  { concepto: "Desmontar y montar pito caracol", precio: 10, edison: null },
  { concepto: "Desmontar y montar Radio", precio: 25, edison: null },
  { concepto: "Cambio de retrovisor", precio: 10, edison: null },
  { concepto: "Cambio de correa de Aire Acondicionado", precio: 25, edison: null },
  { concepto: "Cambio de bushing de barra estabilizadora I-10", precio: 15, edison: 25 },
  { concepto: "Cambio de toma de agua", precio: 15, edison: null },
  { concepto: "Cambio de viga de impacto", precio: 25, edison: null },
  { concepto: "Cambio de marco de radiador", precio: 25, edison: 50 },
  { concepto: "Reparar caña de direccion", precio: 65, edison: null },
  { concepto: "Vacio y Limpieza del Sistema, valvula de expansion, condensador, carga de gas", precio: 35, edison: null },
  { concepto: "Reparar Cremallera", precio: 45, edison: 55 },
];

